name: followup
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  charts_flutter: ^0.12.0
  shared_preferences: ^2.1.2
  validators: ^3.0.0
  image_picker: ^0.8.7+5
  fluttertoast: ^8.2.1
  google_fonts: ^3.0.1
  file_picker: ^5.3.2
  dropdown_search: ^5.0.6
  multi_select_flutter: ^4.0.0
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter_local_notifications: ^14.0.0+1
  firebase_core_platform_interface: ^4.7.0
  flutter_native_splash: ^2.3.1
  firebase_analytics: ^10.0.1
  get: ^4.6.5
  audioplayers: ^4.1.0
  just_audio: ^0.9.34
  flutter_sound: ^8.1.9
  permission_handler: ^8.1.2
  path: ^1.8.0
  assets_audio_player: ^3.0.3+3
  intl: ^0.17.0
  record_mp3: ^3.0.0
  flutter_typeahead: ^4.6.2
  uuid: ^3.0.7
  flutter_image_compress: ^2.0.4
  location: ^5.0.3
  url_launcher: ^6.1.14
  whatsapp_unilink: ^2.1.0
  device_info: ^2.0.3
  razorpay_flutter: ^1.3.6
  sizer: ^2.0.15
  camera: ^0.9.4+5
  fl_chart: ^0.68.0
  audio_session: ^0.1.20
  flutter_easyloading:
  http:
  jwt_decoder:
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  lottie:
  animate_do: ^3.1.2
  firebase_auth:
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ab-logo.png"
  flutter_lints: ^2.0.0

  flutter_native_splash: ^2.3.1

flutter_native_splash:
  image: "assets/ab-logo.png"
flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/logo.png
   - assets/ab-logo.png
   - assets/recording.aac

